# Generated by Django 4.1.5 on 2023-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(default=False, max_length=255)),
                ("duration", models.IntegerField()),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
            },
        ),
    ]
